# set 'C-b' to prefix key
set -g prefix C-b

# ウィンドウのインデックスを1から始める
set -g base-index 1

# キーストロークのディレイを減らす
set -sg escape-time 1

# ペインのインデックスを1から始める
setw -g pane-base-index 1

# 設定ファイルをリロードする
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# | でペインを縦に分割する
bind | split-window -h

# - でペインを横に分割する
bind - split-window -v

# 256色端末を使用する
set -g default-terminal "screen-256color"

##### ステータスバー

### 左
set-option -g status-left-length 20
set-option -g status-left "#[fg=color255,bg=color240] #S #[default]"

# 色を設定する
set -g status-fg black
set -g status-bg white

# ウィンドウリストの色を設定する
setw -g window-status-fg black
setw -g window-status-bg default
setw -g window-status-attr dim

# アクティブなウィンドウを目立たせる
setw -g window-status-current-fg green
setw -g window-status-current-bg yellow
setw -g window-status-current-attr bright

# ペインボーダーの色を設定する
set -g pane-border-fg green
set -g pane-border-bg black
